apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: ghcr.io/bjw-s-labs/helm
    targetRevision: "5.0.0"
    chart: app-template
    helm:
      valueFiles:
      - $values/values/keycloak/keycloak/base/values.yaml
      - $values/values/keycloak/keycloak/homelab/values.yaml
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: main
    path: manifests/keycloak/keycloak
  destination:
    name: in-cluster
    namespace: keycloak
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - IncludeMutationWebhook=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - ServerSideDiff=true
    - Validate=false
