replicas: 2

#serviceMonitor:

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    memory: 1Gi

persistence:
  enabled: false # Will use pg

grafana.ini:
  database:
    type: postgres
    host: grafana-pg-rw.monitoring.svc.cluster.local:5432
    name: app
    user: app
    ssl_mode: require     # CNPG enables TLS by default

envValueFrom:
  GF_DATABASE_PASSWORD:
    secretKeyRef:
      name: grafana-pg-app
      key: password

extraSecretMounts:
  - name: cnpg-ca
    mountPath: /etc/ssl/certs/cnpg-ca.crt
    subPath: ca.crt
    secretName: grafana-pg-ca
    readOnly: true

datasources: {}

dashboardProviders: {}

sidecar:
  alerts:
    enabled: true
  dashboards:
    enabled: true
  datasources:
    enabled: true
  plugins:
    enabled: true
