apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ai-registry-pg
  namespace: agentic
spec:
  instances: 3

  storage:
    size: 5Gi

  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
