apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: loki-user
spec:
  store: main
  displayName: "lokiUser"
  #quotas:
  #  maxBuckets: 100
  #  maxSize: 10G
  #  maxObjects: 10000
  #capabilities:
  #  user: "*"
  #  bucket: "*"
  #opMask:
  #  - read
  #  - write
  #  - delete