resources:
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.66.1/cdi-operator.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.66.1/cdi-cr.yaml
