apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://helm.cilium.io/
    targetRevision: "1.20.0"
    chart: cilium
    helm:
      valueFiles:
      - $values/values/kube-system/cilium/base/values.yaml
      - $values/values/kube-system/cilium/homelab/values.yaml
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: "main"
    ref: values
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: "main"
    path: manifests/kube-system/cilium/
  destination:
    name: in-cluster
    namespace: kube-system
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: cilium-ca
    namespace: kube-system
    jqPathExpressions:
    - '.data'
    - '.data["ca.crt"]'
    - '.data["ca.key"]'
  - group: ""
    kind: Secret
    name: hubble-server-certs
    namespace: kube-system
    jqPathExpressions:
    - '.data'
    - '.data["ca.crt"]'
    - '.data["tls.crt"]'
    - '.data["tls.key"]'
  syncPolicy:
    #automated:
    #  selfHeal: true
    #  prune: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - IncludeMutationWebhook=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - ServerSideDiff=true
    - Validate=false
