apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multus-cni
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: "main"
    path: manifests/kube-system/multus-cni/
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    #automated:
    #  selfHeal: true
    #  prune: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - IncludeMutationWebhook=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - ServerSideDiff=true
    - Validate=false
