apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:             # <-- used to trigger all LB services
        matchExpressions:
         - {key: randomKey, operator: NotIn, values: ['never-used-value']}
