apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- multus-daemonset-thick.yml
- nad-untagged.yaml
- nad-vlan-111.yaml
- nad-vlan-112.yaml

patches:
- path: patches/fix-netns-volume.yaml
- path: patches/resource-limits.yaml
- path: patches/cilium-install-cni.yaml
