resources:
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/v4.2.4/deployments/multus-daemonset-thick.yml
  - nad-10-servers.yaml
  - nad-11-computers.yaml
  - nad-110-k8s-loadbalancer.yaml

images:
  - name: ghcr.io/k8snetworkplumbingwg/multus-cni
    newTag: v4.2.4

patches:
  - target:
      kind: DaemonSet
      name: kube-multus-ds
    patch: |
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: kube-multus-ds
        namespace: kube-system
      spec:
        template:
          spec:
            initContainers:
              - name: install-multus-binary
                command:
                  - "/usr/src/multus-cni/bin/install_multus"
                  - "-d"
                  - "/host/opt/cni/bin"
                  - "-t"
                  - "thick"
            containers:
              - name: kube-multus
                resources:
                  limits:
                    cpu: 300m
                    memory: 150Mi
                  requests:
                    cpu: 200m
                    memory: 100Mi
                volumeMounts:
                  - name: host-run-netns
                    mountPath: /run/netns
                    mountPropagation: HostToContainer
            volumes:
              - name: host-run-netns
                hostPath:
                  path: /var/run/netns/