# VLAN 112 - update master to match the VLAN sub-interface on your nodes (e.g. eth0.112, bond0.112)
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-112
  namespace: kube-system
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vlan-112",
      "type": "macvlan",
      "master": "eth0.112",
      "mode": "bridge",
      "ipam": {
        "type": "dhcp"
      }
    }
