apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentregistry
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: ghcr.io/agentregistry-dev/agentregistry/charts
    targetRevision: "0.4.0"
    chart: agentregistry
    helm:
      valueFiles:
      - $values/values/agentic/agentregistry/base/values.yaml
      - $values/values/agentic/agentregistry/homelab/values.yaml
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: "main"
    ref: values
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: "main"
    path: manifests/agentic/agentregistry/
  destination:
    name: in-cluster
    namespace: agentic
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - IncludeMutationWebhook=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - ServerSideDiff=true
    - Validate=false
