---
server:
  insecure: true
  httproute:
    enabled: true
    parentRefs:
      - name: homelab
        namespace: envoy-gateway
    hostnames:
      - argocd.newgamer.lan
    servicePort: 80
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /
        backendRefs:
         - name: argocd-server
           port: 80
        filters:
          - type: RequestHeaderModifier
            requestHeaderModifier:
              set:
                - name: X-Forwarded-Proto
                  value: https
  
  grpcroute:
    enabled: true
    parentRefs:
      - name: homelab
        namespace: envoy-gateway
    hostnames:
      - argocd.newgamer.lan
    rules:
      - matches:
        - headers:
            - name: Content-Type
              type: RegularExpression
              value: "^application/grpc.*$"

argocd-cmd-params-cm:
  data:
    server.insecure: "true"
