---
server:
  httproute:
    enabled: true
    parentRefs:
      - name: homelab
        namespace: envoy-gateway
    hostnames:
      - argocd.newgamer.lan
  
  grpcroute:
    enabled: true
    parentRefs:
      - name: homelab
        namespace: envoy-gateway
    hostnames:
      - argocd.newgamer.lan