apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.jetstack.io
    targetRevision: "v1.20.2"
    chart: cert-manager
    helm: 
      valueFiles:
      - $values/values/cert-manager/cert-manager/base/values.yaml
      - $values/values/cert-manager/cert-manager/homelab/values.yaml
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: "main"
    ref: values
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: "main"
    path: manifests/cert-manager/cert-manager
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    #automated:
    #  selfHeal: true
    #  prune: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - IncludeMutationWebhook=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - ServerSideDiff=true
    - Validate=false