apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "29.0.0"
    chart: prometheus-operator-crds
    helm:
      valueFiles:
      - $values/values/monitoring/prometheus-crds/base/values.yaml
      - $values/values/monitoring/prometheus-crds/homelab/values.yaml
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: "main"
    ref: values
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    #automated:
    #  selfHeal: true
    #  prune: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - IncludeMutationWebhook=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - ServerSideDiff=true
    - Validate=false
