serviceMonitor:
  enabled: true

sources:
  - ingress
  - service
  - gateway-httproute
  - gateway-tlsroute
  - gateway-tcproute
  - gateway-udproute

policy: sync

env:
  - name: ETCD_URLS
    value: https://etcd.external-dns:2379

extraVolumes:
  - name: etcd-client-tls
    secret:
      secretName: etcd-client-tls

extraVolumeMounts:
  - name: etcd-client-tls
    mountPath: /etc/ssl/certs/etcd-client-tls
    readOnly: true

extraArgs:
  tls-ca: /etc/ssl/certs/etcd-client-tls/ca.crt
  tls-key: /etc/ssl/certs/etcd-client-tls/tls.key
  tls-cert: /etc/ssl/certs/etcd-client-tls/tls.crt

domainFilters:
  - newgamer.lan

provider:
  name: coredns

rbac:
  create: true

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi