serviceMonitor:
  enabled: true

sources:
  - ingress
  - service
  - gateway-httproute
  - gateway-tlsroute
  - gateway-tcproute
  - gateway-udproute

policy: sync

env:
  - name: ETCD_URLS
    value: https://etcd.external-dns:2379

extraVolumeMounts:
  - name: etcd-client-tls
    mountPath: /etc/ssl/certs/etcd-client-tls
    readOnly: true

domainFilters:
  - newgamer.lan

provider:
  name: etcd

rbac:
  create: true

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi