apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-bucket
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete               # or Retain to keep data after OBC deletion
volumeBindingMode: Immediate
parameters:
  objectStoreName: main
  objectStoreNamespace: rook-ceph
  region: us-east-1                 # arbitrary; used in SDK config