apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool-nvme
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 2
    requireSafeReplicaSize: true
  parameters:
    pg_autoscale_mode: 'on'
    #pg_num: '128'
    #pgp_num: '128'
    #target_size_ratio: '0.8'
  deviceClass: nvme
