apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: docker.io/envoyproxy
    targetRevision: "1.7.3"
    chart: gateway-helm
    helm:
      valueFiles:
      - $values/values/envoy-gateway/envoy-gateway/base/values.yaml
      - $values/values/envoy-gateway/envoy-gateway/homelab/values.yaml
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: "main"
    ref: values
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: "main"
    path: manifests/envoy-gateway/envoy-gateway
  destination:
    name: in-cluster
    namespace: envoy-gateway
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: self-signed-cert-for-mutating-webhook
    namespace: envoy-gateway
    jqPathExpressions:
    - '.data'
    - '.data["ca.crt"]'
    - '.data["tls.crt"]'
    - '.data["tls.key"]'
  syncPolicy:
    #automated:
    #  selfHeal: true
    #  prune: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - IncludeMutationWebhook=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - ServerSideDiff=true
    - Validate=false
