config:
  persistence:
    size: 10Gi

route:
  main:
    enabled: true
    hostnames:
      - seerr.newgamer.lan
    httpsRedirect: false
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: homelab
      namespace: envoy-gateway
      sectionName: https

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 1Gi