apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: ghcr.io/kserve/charts
    targetRevision: v0.20.0
    chart: kserve-crd
    helm: {}
  - repoURL: ghcr.io/kserve/charts
    targetRevision: "v0.20.0"
    chart: kserve-resources
    helm:
      valueFiles:
      - $values/values/kserve/kserve/base/values.yaml
      - $values/values/kserve/kserve/homelab/values.yaml
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: "main"
    ref: values
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: "main"
    path: manifests/kserve/kserve/
  destination:
    name: in-cluster
    namespace: kserve
  syncPolicy:
    #automated:
    #  selfHeal: true
    #  prune: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - IncludeMutationWebhook=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - ServerSideDiff=true
    - Validate=false
