apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seerr
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: ghcr.io/seerr-team/seerr
    targetRevision: "3.5.1"
    chart: seerr-chart
    helm:
      valueFiles:
      - $values/values/media-management/seerr/base/values.yaml
      - $values/values/media-management/seerr/homelab/values.yaml
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: "main"
    ref: values
  #- repoURL: https://github.com/Haibread/homelab-infra.git
  #  targetRevision: "main"
  #  path: manifests/media-management/seerr
  destination:
    name: in-cluster
    namespace: media-management
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
    #automated:
    #  selfHeal: true
    #  prune: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - IncludeMutationWebhook=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - ServerSideDiff=true
    - Validate=false