apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tautulli
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: ghcr.io/bjw-s-labs/helm
    targetRevision: "5.0.1"
    chart: app-template
    helm:
      valueFiles:
      - $values/values/media-management/tautulli/base/values.yaml
      - $values/values/media-management/tautulli/homelab/values.yaml
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: "main"
    ref: values
  - repoURL: https://github.com/Haibread/homelab-infra.git
    targetRevision: "main"
    path: manifests/media-management/tautulli
  destination:
    name: in-cluster
    namespace: media-management
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - IncludeMutationWebhook=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - ServerSideDiff=true
    - Validate=false
